### ISSUE TITLE
Home page updates

### ISSUE THREAD

**Issue by geoffsimons** [mondaynightpinball/main#22]
* Remove lingering season 8 info (DONE)
* Update a What's New section to talk about some of the new rules, new teams, and so on. (DONE)
* (#4) Link to GitHub issues, maybe as part of a developer section. (DONE)
* Contact us (ideally email address would be loaded from .env) (#33)
* Mission statement / Core Values (DONE)
* Link for player lookup (DONE)

**Comment by madcock** [comment]
- First link under "Some Helpful Links" on main page is broken. Should point to same place as Rules link from drop-down menu.

**Comment by geoffsimons** [comment]
Added new issue for contact page, since that is outside the scope of the home page (aside from a link, which should be added when the contact page is available).
